#language: java
#jdk:
#- oraclejdk8

#branches:
#  only:
#  - release

#cache:
#  directories:
#  - $HOME/.m2 # speed up maven

addons:
  ssh_known_hosts: prod.cmlteam.com

before_deploy:
- openssl aes-256-cbc -K $encrypted_a8cfb19c2c84_key -iv $encrypted_a8cfb19c2c84_iv
  -in deploy_rsa.enc
  -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ./.travis.deploy.sh
#  on:
#    branch: release
